name: Page on Push

on:
  push:
    branches:
      - master


permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai

      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: "19"

      - name: Install Dependencies
        run: yarn install

      - name: Build assets
        run: yarn docs:build

      - name: Make CNAME file
        run: yarn docs:cname

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: gh-pages
          build_dir: docs/.vuepress/dist

        env:
          GITHUB_TOKEN: ${{ secrets.COOLPLAYLIN_BOT_TOKEN }}